version: '3.3'
services:
  server:
    restart: always
    build: ./bank_service/.
    #deploy:
      #resources:
          #limits:
            #cpus: "0.50"
            #memory: 512M
    expose:
      - 8080
    ports:
      - 7777:8080
    depends_on:
      mysqldb:
        condition: service_healthy

  mysqldb:
    restart: always
    image: mysql
    environment:
      - MYSQL_DATABASE=Bank_db
      - MYSQL_USER=springuser
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_PORT=3306
    volumes:
      - ./initdb/CreateTables.sql:/docker-entrypoint-initdb.d/CreateTables.sql
    ports:
      - 3306:3306
    expose:
      - 3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
