version: "3.1"

services:

  db:
    image: postgres
    ports:
      - 5433:5432
    env_file:
      - ".env"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
    networks:
      - store
    restart: always

  django:
    build:
      context: .
    env_file:
      - ".env"
    volumes:
      - .:/src
    networks:
      - store
    restart: always
    depends_on:
      - db

  nginx:
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    networks:
      - store
    depends_on:
      - db
      - django
    ports:
      - "4444:8080"
    volumes:
      - ./static/:/static
    restart: always

networks:
  store:
    driver: bridge


