version: "3.1"

x-healthcheck: 
  &healthcheck
  test: curl -f http://localhost/
  interval: 30s
  timeout: 10s
  retries: 5
  start_period: 10s

services:

  db:
    container_name: database
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - ".env"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/
    networks:
      - store
    restart: always
    healthcheck:
      << : *healthcheck
      test: pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-db}

  django:
    container_name: django
    image: ${IMAGE_BACKEND:-ghcr.io/n57uctf/store-api-backend:main}
    build:
      context: .
    ports:
      - 8000:8000
    env_file:
      - ".env"
    volumes:
      - .:/src
    networks:
      - store
    restart: always
    depends_on:
      db:
        condition: service_healthy

  nginx:
    image: ${IMAGE_FRONTEND:-ghcr.io/n57uctf/store-api-frontend:main}
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    networks:
      - store
    depends_on:
      django:
        condition: service_started
    ports:
      - "8080:8080"
    volumes:
      - ./static/:/static
    restart: always

networks:
  store:
    driver: bridge


