version: "3.1"

x-healthcheck:
  &healthcheck
  test: curl -f http://localhost/
  interval: 30s
  timeout: 10s
  retries: 5
  start_period: 10s

services:

  db:
    container_name: database
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - ".env"
    restart: always
    healthcheck:
      << : *healthcheck
      test: pg_isready -U ${POSTGRES_USER:-admin} -d ${POSTGRES_DB:-db}

  django:
    container_name: django
    image: ${IMAGE_BACKEND:-ghcr.io/n57uctf/store-api-backend:main}
    build:
      context: .
    ports:
      - 8000:8000
    env_file:
      - ".env"
    volumes:
      - .:/src
    restart: always
    depends_on:
      - db
    healthcheck:
      << : *healthcheck
      test: curl http://127.0.0.1:8000/

  nginx:
    image: ${IMAGE_FRONTEND:-ghcr.io/n57uctf/store-api-frontend:main}
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    depends_on:
      - django
    ports:
      - "8080:8080"
    volumes:
      - ./static/:/static
    restart: always
    healthcheck:
      << : *healthcheck
      test: curl http://127.0.0.1:8080/

